### ISSUE TITLE
Confirmation email not sent

### ISSUE THREAD

**Issue by aiaf** [ledstrain/wiki.ledstrain.org#86]
Apologies if this is not the right place, but I'm not getting my confirmation email for the LEDStrain forums. Did check my spam folders and everything and tried to re-send many times.

**Comment by tyler71** [comment]
Sorry for the trouble, please send an email to issues at ledstrain.org

https://ledstrain.org/p/7-support

I'll look into this soon

**Comment by aiaf** [comment]
Received all the emails earlier this morning.
